receivers:
  filelog: # Reads logs from files
    include: [ "/var/log/*.log" ] 
    start_at: end

  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"  # Default for OTLP gRPC
      http:
        endpoint: "localhost:4318"  # Default for OTLP HTTP
        
exporters:
  otlp:
    endpoint: "10.148.0.7:4317"  # The endpoint where the central collector is listening

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [otlp]
